# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum up a matrix
#' 
#' @param m A numeric matrix
#' @export
sumCpp <- function(m) {
    .Call(`_simscaleR_sumCpp`, m)
}

#' Transpose a matrix
#' 
#' @param m A numeric matrix
#' @export
tCpp <- function(m) {
    .Call(`_simscaleR_tCpp`, m)
}

